### ISSUE TITLE
Request for port

### ISSUE THREAD

**Issue by TerensTare** [mozeal/SDL_gui#13]
Hey there, @mozeal . Your library looks awesome and really useful. I was thinking of making a port of it to GoLang to use it together with SDL2, however I thought I should write this issue before to get your permission.

**Comment by EwanGreen4** [comment]
I'm aware this issue is almost a year old. However, I still felt this was worth commenting:

Given you include the MIT license notices (copyright notice & permission notice, both in SDL_gui/LICENSE), you have the ability to "deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so".

This is just a paraphrased section of the MIT license. It is permissive for everything you would like to do with it.

[License](https://github.com/mozeal/SDL_gui/blob/master/LICENSE)

**Comment by TerensTare** [comment]
Thanks very much for replying. I didn't check the license before😅
However, I left the porting aside, as I am focusing on a C++ project for now. In this case, I am closing the issue. Thank you once again.
